### ISSUE TITLE
Get followers non followers

### ISSUE THREAD

**Issue by amrilkholid** [charlieAndroidDev/Instagram4Android#105]
Is it possible to get lists of my following users who don't follow back with this API ?

**Comment by cmoutafidis** [comment]
I am sure you can get a list of users you are following and compare it with a list of users who are following you. At least this is how I implemented it. Maybe there is a faster way but I am not aware of it.

**Comment by cellojaan** [comment]
You can dedect unfollowers like this:

 for (InstagramUserSummary i : following) {
                    for (InstagramUserSummary j : followers) {
                        if (i.equals(j)) {
                            unfollowers.remove(i);
                            break;
                        }
                    }
                }

**Comment by amrilkholid** [comment]
Thanks, will try it,
