### ISSUE TITLE
64-bit support

### ISSUE THREAD

**Issue by emiliogaines** [charlieAndroidDev/Instagram4Android#109]
Will we be seeing 64-bit support for this library?
It seems that both ffmpeg and OKHttp isn't updated to 64-bit in this library and therefor we cannot publish apps made with this library. (I'm not 100% sure it's these two) but the issue still stands.

**Comment by cellojaan** [comment]
Put this code in your app/build.grandle under the **VersionName**:

`ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'`

**Comment by emiliogaines** [comment]
> Put this code in your app/build.grandle under the **VersionName**:
> 
> `ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'`

Doesn't work. Still gives the same error.

**Comment by vadimTovstik** [comment]
Did someone solve the problem? Oh sh*, I have the whole application built on this library

**Comment by vadimTovstik** [comment]
@charlieAndroidDev , please, include supports of x64, beacause I can't upload this to Google Play. I have deadline now.

**Comment by cellojaan** [comment]
> > Put this code in your app/build.grandle under the **VersionName**:
> > `ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'`
> 
> Doesn't work. Still gives the same error.

It's must work. What kind of error you got it?

**Comment by emiliogaines** [comment]
> > > Put this code in your app/build.grandle under the **VersionName**:
> > > `ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'`
> > 
> > 
> > Doesn't work. Still gives the same error.
> 
> It's must work. What kind of error you got it?

It gives exactly the same error when uploading to Google Play as stated [here](https://developer.android.com/distribute/best-practices/develop/64-bit).

**Comment by vadimTovstik** [comment]
Yes, I get exactly the same error.

**Comment by vadimTovstik** [comment]
> > > Put this code in your app/build.grandle under the **VersionName**:
> > > `ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'`
> > 
> > 
> > Doesn't work. Still gives the same error.
> 
> It's must work. What kind of error you got it?

Kind of error.

Warning
This release is not compliant with the Google Play 64-bit requirement
The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: 1.
From August 1, 2019 all releases must be compliant with the Google Play 64-bit requirement.
Include 64-bit and 32-bit native code in your app. Use the Android App Bundle publishing format to automatically ensure that each device architecture receives only the native code it needs. This avoids increasing the overall size of your app.

**Comment by AndreaCioccarelli** [comment]
This library is dead, build up your own, it will pay off eventually (I eventually written my own Kotlin project which improved performances by 10 times, this one really sucks)

**Comment by vadimTovstik** [comment]
I solved it this way. Just excluded some x32 libraries

put packagingOptions block to app module file build.gradle
android {
    ...
    packagingOptions {
        exclude 'lib/x86/libARM_ARCH.so'
        exclude 'lib/armeabi/libARM_ARCH.so'
        exclude 'lib/armeabi-v7a/libARM_ARCH.so'
    }
}

After that Google Play approved my realese bundle. Happy coding.

**Comment by charlieAndroidDev** [comment]
This library is unmaintained and will be removed soon.  Instagram is cracking down on use of it's private API as seen here (library this is based on): https://github.com/mgp25/Instagram-API

If you create real apps and deploy to Google Play, expect to be banned or your apps to be removed.  This library is not in a good state and is only really meant for toy apps.  It was a fun reverse engineering project but not suitible for real apps.
