### ISSUE TITLE
Implementation issue

### ISSUE THREAD

**Issue by jackaru** [charlieAndroidDev/Instagram4Android#12]
After added the library and maven on gradle, I tested the empty build I got this error:

![image](https://user-images.githubusercontent.com/21238513/30786705-a7084574-a17a-11e7-9b71-ba2085f4256d.png)
`

**Comment by charlieAndroidDev** [comment]
Try adding this to your _project_ level build.gradle:

```
packagingOptions{
    exclude 'META-INF/DEPENDENCIES'
    exclude 'META-INF/NOTICE'
    exclude 'META-INF/LICENSE'
}
```

**Comment by jackaru** [comment]
Solved, thanks! Keep work on this awesome api
