### ISSUE TITLE
login

### ISSUE THREAD

**Issue by rasoolta** [charlieAndroidDev/Instagram4Android#15]
whene i use this code 
Instagram4Android instagram = Instagram4Android.builder().username(username).password(password).build();
instagram.setup();
instagram.login();
 get this errors for instagram.login()
Error:(22, 24) error: unreported exception IOException; must be caught or declared to be thrown
and
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
when use try catch get this error
android.os.NetworkOnMainThreadException

i set <uses-permission android:name="android.permission.INTERNET"/> in manifest

**Comment by charlieAndroidDev** [comment]
Most of the code you write using this library will use the network.  You therefore need to do it in a background thread, either by using AsyncTask or something like RxJava.
