### ISSUE TITLE
login webveiw??

### ISSUE THREAD

**Issue by rasoolta** [charlieAndroidDev/Instagram4Android#18]
hi
thanks for your lib
how i can use instagram login in web view ??
Markets are not allowed to publish apps not use instagram page in web veiw
can you help me for login instagram with web veiw??
tnx

**Comment by salehmosleh** [comment]
i have this problem , can anybody help me ?!

**Comment by QUIQUELHAPPY** [comment]
No, you can't unless you use the official instagram public api. You could try to implement a facebook login I think
