### ISSUE TITLE
how to set max for InstagramTimelineFeedRequest()

### ISSUE THREAD

**Issue by rasoolta** [charlieAndroidDev/Instagram4Android#19]
hi 
how to set max id for geting posts of timeline
when request to instagram i get one of the posts timeline
how to get more??

**Comment by socioboard** [comment]
Pass the next_id to get next page data
instagram4.sendRequest(new InstagramTimelineFeedRequest(next_id, null));

**Comment by rasoolta** [comment]
tnx
