### ISSUE TITLE
how to get album urls

### ISSUE THREAD

**Issue by rasoolta** [charlieAndroidDev/Instagram4Android#20]
tnx for this lib
how can get links pic or video of albume (media type 8)

**Comment by charlieAndroidDev** [comment]
In the latest library version, you can do this easily:

```
val firstAlbumUrl = item.media_or_ad.carousel_media[0].image_versions2.candidates[0].url
```

Iterate over all `carousel_media` items to get all photos/videos in the album.

**Comment by rasoolta** [comment]
tnx 👍 :)

**Comment by kukalajet** [comment]
@rasoolta @charlieAndroidDev 
How can I get a video url? It just returns pics link.
