### ISSUE TITLE
Error:Execution failed for task ':app:processDebugManifest'

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [charlieAndroidDev/Instagram4Android#22]
Hello, I'm trying to import this lib, I've added the maven dependency like [this](https://i.imgur.com/WUD5zAb.png), and compile 'com.github.charlieAndroidDev:Instagram4Android:0.2.2' inside the app dependencies, but I get the following error.

```
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs
```

I don't know exactly what to do... 😢

**Comment by charlieAndroidDev** [comment]
What I do when that happens (not just this library), is I go to **build** -> **clean project**  and then **build** -> **rebuild**

**Comment by QUIQUELHAPPY** [comment]
I'm getting the same... I've tried with different releases, I don't get the error if I don't import this lib, [here's a video](https://www.youtube.com/watch?v=KrT9ujpM3mQ&feature=youtu.be), I don't know if I'm doing something wrong 🤔

**Comment by charlieAndroidDev** [comment]
Check your cradle console while building to see a more detailed reason behind the failure.

**Comment by QUIQUELHAPPY** [comment]
I found the solution.
The **min SDK have to be n19 (Android 4.4) but it was set to n15**, I think this should be annotated in the installation section of README.md, also, in my app manifest I had this **android:theme=@ style/AppTheme.NoActionBar"** and apparently this doesn't make it compatible with this lib, replacing that value with AppTheme without any subclass should fix the problem 👍 

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme. -->NoActionBar <--">
        <activity
            android:name=".sodge"
            android:noHistory="true"
            android:theme="@style/AppTheme.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity ...

**Comment by charlieAndroidDev** [comment]
I did actually know about minSDK 19 but I thought most people would be targeting that or above.  I have no idea why **NoActionBar** gave an error, I'll have a look.

**Comment by charlieAndroidDev** [comment]
Try using **AppTheme.NoActionBar** on each of your Activities instead.
