### ISSUE TITLE
Login session

### ISSUE THREAD

**Issue by logan23** [charlieAndroidDev/Instagram4Android#26]
There is a kind of possibility not to store login/password?
For example as it is done in php library:
Your sessions will be stored a sessions/username/ folder by default, if you're using the file-based settings backend. If you set use other custom settings path, a username folder will be created under it. By default, the hierarchy is as follows:...

**Comment by charlieAndroidDev** [comment]
This is very easy to implement yourself, you could store the user/pass in sharedPreferences (encrypted of course) and just login again automatically when necessary.

**Comment by mominak47** [comment]
But login every time might block your account. Instagram can detect you every time you login.
