### ISSUE TITLE
Instagram feed result is showing empty.

### ISSUE THREAD

**Issue by AwadheshKumarG** [charlieAndroidDev/Instagram4Android#3]
InstagramFeedResult feed = instagram.sendRequest(new InstagramUserFeedRequest());
            
                for (InstagramFeedItem feedResult : feed.getItems()) {
                    System.out.println("Post ID: " + feedResult.getPk());
                    System.out.println("Post Like: " + feedResult.getLike_count());
                    System.out.println("Post Likertrgfdg: " + feedResult.getImage_versions2());
                }

**Comment by charlieAndroidDev** [comment]
try ```feed.getRanked_items()```
