### ISSUE TITLE
Does not connect with Facebook token

### ISSUE THREAD

**Issue by DigitalKoi** [charlieAndroidDev/Instagram4Android#31]
checkpoint_url=null)`InstagramLoginResult(super=StatusResult(super=dev.niekirk.com.instagram4android.requests.payload.InstagramLoginResult@35d4228a, status=fail, message=You can log into Instagram with your username or create a new account.), logged_in_user=null, error_type=fb_no_contact_point_found, checkpoint_url=null)`
I do something wrong?

**Comment by charlieAndroidDev** [comment]
Yep that issue means you have an invalid FB access token.  To get the correct access token please use webview FB login, along with Instagrams App ID (do not create a Facebook app in their portal, use Instagram details instead)

Their app ID is: 124024574287414

**Comment by Soydasm** [comment]
@charlieAndroidDev hello Charlie, thanks for the library. Can you tell us, how can we login facebook with instagram app id? what does it mean?
