### ISSUE TITLE
Basic example

### ISSUE THREAD

**Issue by dakiesse** [charlieAndroidDev/Instagram4Android#41]
Hey! I'm not from Java world and I have come across the next problem. I have the code:
```
@ReactMethod
public void login(Callback successCallback) {
    Instagram4Android instagram = Instagram4Android.builder().username("myLogin").password("myPass").build();

    instagram.setup();
    try {
        InstagramLoginResult result = instagram.login();
        successCallback.invoke(result);
    } catch (Exception e) {
        successCallback.invoke(e.getMessage());
    }
}
```
Executing was being gone into 'catch' block with message: `Cannot convert argument of type class dev.niekirk.com.instagram4android.requests.payload.InstagramLoginResult`.

What have I done wrong?

**Comment by charlieAndroidDev** [comment]
I'm assuming your `successCallback.invoke` method needs to take a `String` and not an `InstagramLoginResult`.  Try `result.getStatus` instead of `result`.
