### ISSUE TITLE
HTTP 431

### ISSUE THREAD

**Issue by cagdasc** [charlieAndroidDev/Instagram4Android#43]
Hi,

I want to fetch user follower list and this user has 8k followers. After a while content was empty and it throws JsonParseException and status was 431. I see cookie size increase and I don't know how can I clear cookie or it's about cookie size?
Thank you.
```
public List<InstagramUserSummary> getUserFollowingList(long userId) throws IOException {
        List<InstagramUserSummary> users = new ArrayList<>();
        InstagramGetUserFollowersResult userFollowersResult;
        String maxId = null;
        do {
            InstagramGetUserFollowingRequest s = new InstagramGetUserFollowingRequest(userId, maxId);
            userFollowersResult = instagram4j.sendRequest(s);
            instagram4j.setup();
            users.addAll(userFollowersResult.getUsers());
            maxId = userFollowersResult.getNext_max_id();
            instagram4j.setup();
        } while (userFollowersResult.isBig_list());

        return users;

    }
```

**Comment by mcsentul** [comment]
same here, no result for follower list,

**Comment by charlieAndroidDev** [comment]
It looks like you're using instagram4j man.  If you aren't then Instagram is probably blocking you temporarily for non human behaviour.  Try adding a short delay between each request.

**Comment by cagdasc** [comment]
@charlieAndroidDev I put in delay about 25sec. there is no difference.

**Comment by mcsentul** [comment]
@charlieAndroidDev work on a user has about 4k follower,

in 14k followers

com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
..

how to handle large followers and get it into database?

**Comment by cagdasc** [comment]
@mcsentul I trace calls and found http 431 response code. CookieStore allways addAll and it's size was increase. Maybe cookie size can control with defined limit. You can import tihs module in your project and try cookie modification, I will do this.

I think the problem was here.
```
public void setup() {

        /*
        if (this.username.length() < 1) {
            throw new IllegalArgumentException("Username is mandatory.");
        }
        if (this.password.length() < 1) {
            throw new IllegalArgumentException("Password is mandatory.");
        }*/

        this.deviceId = InstagramHashUtil.generateDeviceId(this.username, this.password);
        this.uuid = InstagramGenericUtil.generateUuid(true);

        client = new OkHttpClient.Builder()
                .cookieJar(new CookieJar() {

                    @Override
                    public void saveFromResponse(HttpUrl url, List<Cookie> cookies) {
                        //Log.d("I4A", "Added cookies!");
                        cookieStore.addAll(cookies);
                    }

                    @Override
                    public List<Cookie> loadForRequest(HttpUrl url) {
                        List<Cookie> validCookies = new ArrayList<>();
                        for(Cookie cookie: cookieStore) {

                            //Log.d("I4A", "Cookie: " + cookie.name());

                            if(cookie.expiresAt() < System.currentTimeMillis()) {

                            } else {
                                validCookies.add(cookie);
                            }

                        }

                        return validCookies;
                    }
                })
                .build();

    }
```

**Comment by cagdasc** [comment]
@charlieAndroidDev  Do you interested with this subject? Library can not add a project. It gives several errors.

**Comment by cagdasc** [comment]
@mcsentul you can extends Instagram4Android and override setup metod. If cookie size greater than 100 you can delete first 15(a lot of try) cookies. This works but when you want to second request for followers list, result was "login_required". I will try store login cookies and delete others or add another cookie handling method.
