### ISSUE TITLE
[Solution]   Failed to resolve  compile 'com.github.charlieAndroidDev:Instagram4Android:v0.1.11' 

### ISSUE THREAD

**Issue by biswatmanayak** [charlieAndroidDev/Instagram4Android#5]
In case anyone facing this issue remove 'v' from " **v0.1.11** " and sync. 

http://prntscr.com/gb1s2k

@charlieAndroidDev please update the readme

**Comment by charlieAndroidDev** [comment]
Oh yeah, I was so happy I fixed an issue I just did the readme as quick as possible and screwed it up.  Will change it now
