### ISSUE TITLE
Is this library legal ?

### ISSUE THREAD

**Issue by developeralp** [charlieAndroidDev/Instagram4Android#55]
Hello,

This library looks amazing.
I want to use your library but i also want to publish my app on google play store ?

Is it ok to publish my app to play store ?

Has anyone tried this ?

**Comment by RonArel** [comment]
I was just about to post a question asking the same thing... I need an answer, too.

**Comment by AlexByte** [comment]
:-D

**Comment by charlieAndroidDev** [comment]
Many apps on the play store use the private API which this library provides access to.  

Example: https://play.google.com/store/apps/details?id=io.storysave.android

This app doesn't use my library but the coder basically made their own and accesses all the same endpoints.  With over 500k downloads if sat you're pretty safe publishing your own apps.  Just don't use copyrighted words in your app name like "instagram" or "ig" or "insta".
