### ISSUE TITLE
How to Persist Instagram4android object ?

### ISSUE THREAD

**Issue by mehhrad** [charlieAndroidDev/Instagram4Android#6]
i'm developing a app with this api.
but user has to wait until Instagram4android login.

is there  a way to not login each time user open app?

can add `toJson()` and `fromJson `methods to `Instagram4Android`

**Comment by charlieAndroidDev** [comment]
The thing is, you will need to have the user signed in if you want to perform any actions.  As this is the private API, Instagram doesn't say how long until the user is de-authenticated so I cannot build that functionality in without loads of testing and if Instagram decides to change that timeout it will have been a lot of work for nothing.

**Comment by mehhrad** [comment]
you're right but this login process is ugly.

what about checking validation of object before sending requests? if the object is not valid anymore then  login again.

let's find a way 
thanks a ton : )

**Comment by charlieAndroidDev** [comment]
Well, I could give it a try.  Give me time though, as I am quite busy right now.  After seeing your response , a solution is possible, I’ll try it out.

**Comment by mehhrad** [comment]
i did it but after about 50 like the insta4android obejct is not valid anymore.

persisting was a useless idea
