### ISSUE TITLE
How to save followers list with InstagramUserSummary model?

### ISSUE THREAD

**Issue by cellojaan** [charlieAndroidDev/Instagram4Android#72]
Hi.
I wanna save in sqlite or sharedprreferences followers list but I can not do that because of InstagramUserSummary model. How we can save it? Any idea?

**Comment by crashfiredeep** [comment]
hi,
Yes you can save as a list in sharedprefrences using the third party library TinyDB(https://github.com/kcochibili/TinyDB--Android-Shared-Preferences-Turbo). If you want to save whole list in sqlite you can create databse with fields as in InstagramUserSummary.

**Comment by cellojaan** [comment]
I find it with tinydb but when try to save followers in tinydb and if followers is more than 7.000, app is freezing. If you help me with this, I can also help you.

**Comment by crashfiredeep** [comment]
Ohhh!!! I have never used TinyDB with that much data. then you must/should use the sqlite for this. because this much data is stored as app data in Shared Preferences. can we connect on twitter ? you can send me url of yours.

**Comment by cellojaan** [comment]
I have no twitter body but you can contact with me from instagram. Username is same

**Comment by cellojaan** [comment]
@crashfiredeep I can save the  the list but not get the list from TinyDB with InstagramUserSummary. You have any ideal about it?

**Comment by crashfiredeep** [comment]
you can get the list by using get methods according to your requirement using TinyDB object and assign to type of variable/object that is returned.

**Comment by cellojaan** [comment]
I could not make it can you make a sample please? If I resolve this, then I can make the recently unfollowers @crashfiredeep

**Comment by cellojaan** [comment]
I fixed. Thanks.
