### ISSUE TITLE
InstagramTagFeedRequest class is not taking maxId parameter

### ISSUE THREAD

**Issue by biswatmanayak** [charlieAndroidDev/Instagram4Android#9]
It is fetching very few data while searching hashtags, It seems you have not added pagination functionality to it. 

https://github.com/brunocvcunha/instagram4j/blob/750070e5a016330636cb80ec885ad90cf807666e/src/main/java/org/brunocvcunha/instagram4j/requests/InstagramTagFeedRequest.java

Check here for reference

**Comment by charlieAndroidDev** [comment]
I will fix and close this issue tonight, thanks.
